# This is a basic workflow to help you get started with Actions

# 这套工作流程的名称
name: deploy blog

# Controls when the workflow will run
on:
  # 监听push操作
  push:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use
  
  # Allows you to run this workflow manually from the Actions tab
  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# 工作流
jobs:
  # This workflow contains a single job called "build"
  build:
     # 运行环境
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 依赖
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
      - uses: actions/setup-node@v3
      # 安装依赖
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      # 开始打包到服务器
      - name: deploy to staging server
        uses: easingthemes/ssh-deploy@main
        env:
        # SSH_PRIVATE_KEY: 是在服务器上生成的 SSH 私钥，可以使用命令 ssh-keygen -m PEM -t rsa -b 4096 生成，并配置到仓库的 Secrets 中。
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        # ARGS: 默认即可。
          ARGS: "-rltgoDzvO --delete"
        #  需要上传到服务器上的文件的目录
          SOURCE: "dist/"
        # 服务器公网 IP 或域名。
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        #  服务器 SSH 用户名。
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # 文件上传到服务器上保存的目录。
          TARGET: ${{ secrets.REMOTE_TARGET }}
        # 可指定部分文件不上传。
         # EXCLUDE:
