name: Vuepress CI
on:
  # 监听 PUSH 操作
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.0'
    - name: INSTALL
      run: npm install
    - name: BUILD
      run: npm run build
    - name: DEPOLY
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        # ARGS: 默认即可。
          ARGS: '-rltgoDzvO --delete'
        #  需要上传到服务器上的文件的目录
          SOURCE: 'dist/'
        # 服务器公网 IP 或域名。
          REMOTE_HOST: '43.138.140.150'
        #  服务器 SSH 用户名。
          REMOTE_USER: 'root'
        # 文件上传到服务器上保存的目录。
          TARGET: '/home/dev/web'

