# This is a basic workflow to help you get started with Actions

# 这套工作流程的名称
name: deploy blog

# Controls when the workflow will run
on:
  # 监听push操作
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# 工作流
jobs:
  # This workflow contains a single job called "build"
  build:
     # 运行环境
    runs-on: Ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Node.js
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.0'
      # 1.安装依赖
    - name: npm install
      run: npm install
    - name: npm run build

    # 2.生成静态文件
      run: npm run build
      
    # 3.开始打包到服务器
    - name: depoly
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        #需要上传到服务器上的文件的目录
        path: dist/
        #服务器公网 IP 或域名。
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        #服务器 SSH 用户名。
        remote_user: ${{ secrets.REMOTE_USER }}
        #文件上传到服务器上保存的目录。
        remote_path: ${{ secrets.REMOTE_PATH }}
        #远程 ssh 密钥
        remote_key: ${{ secrets.SERVER_SSH_KEY }}
  
    # 4.同步到gitee
    - name: sync_gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        source-repo: "git@github.com:y-jm/blog.git"
        destination-repo: "git@gitee.com:ouyjm/blog.git"


    - name: Fix issue with repository ownership
      run: git config --global --add safe.directory /github/workspace
    
    # 5.同步到coding_net
    - name: sync_coding_net
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.CODING_NET_PRIVATE_KEY }}
      with:
        source-repo: "git@github.com:y-jm/blog.git"
        destination-repo: "git@e.coding.net:jank-yang/blog/Vblog.git"
