name: Vuepress CI
on:
  # 监听 PUSH 操作
  push:
    branches:
      - master
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.0'
    - name: INSTALL
      run: npm install
    - name: BUILD
      run: npm run build
    - name: DEPOLY
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
      # SSH_PRIVATE_KEY: 是在服务器上生成的 SSH 私钥，可以使用命令 ssh-keygen -m PEM -t rsa -b 4096 生成，并配置到仓库的 Secrets 中。
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      # ARGS: 默认即可。
        ARGS: "-rltgoDzvO --delete"
      #  需要上传到服务器上的文件的目录
        SOURCE: "dist/"
      # 服务器公网 IP 或域名。
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #  服务器 SSH 用户名。
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      # 文件上传到服务器上保存的目录。
        TARGET: ${{ secrets.REMOTE_TARGET }}

