name: Node CI test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
      # SSH_PRIVATE_KEY: 是在服务器上生成的 SSH 私钥，可以使用命令 ssh-keygen -m PEM -t rsa -b 4096 生成，并配置到仓库的 Secrets 中。
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      # ARGS: 默认即可。
        ARGS: "-rltgoDzvO --delete"
      #  需要上传到服务器上的文件的目录
        SOURCE: "dist"
      # 服务器公网 IP 或域名。
        REMOTE_HOST: 43.138.140.150
      #  服务器 SSH 用户名。
        REMOTE_USER: root
      # 文件上传到服务器上保存的目录。
        TARGET: /home/dev
      # 可指定部分文件不上传。
        # EXCLUDE:
