name: Deploy test
 
# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master
 
# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
 
      - name: deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
          switches: -avzh
          path: dist/
          remote_path: /home/dev/blog/
          remote_host: xiyangyang.cc
          remote_port: 22
          remote_user: dev
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
