name: sync_to_gitee 
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:y-jm/blog.git"
          destination-repo: "git@gitee.com:ouyjm/blog.git"
